function sl_customization(cm)
    % Change the order of libraries in the Simulink Library Browser. 
    cm.LibraryBrowserCustomizer.applyOrder( ...
        {'Neuromorphic Toolbox/Neural Blocks',-5 ...
        ,'Neuromorphic Toolbox/Secondary Blocks',-4 ...
        ,'Neuromorphic Toolbox/Events Transmission Blocks',-3 ...
        ,'Neuromorphic Toolbox/Quick Insert',-2 ...
        ,'Neuromorphic Toolbox/Quick Insert/Neural Blocks',-5 ...
        ,'Neuromorphic Toolbox/Quick Insert/Secondary Blocks',-4 ...
        ,'Neuromorphic Toolbox/Quick Insert/Events Transmission Blocks',-3} ...
    );
end

