function sl_customization(cm)
    % Change the order of libraries in the Simulink Library Browser. 
    cm.LibraryBrowserCustomizer.applyOrder( ...
        {'NeurCont Toolbox/Neural Blocks',-5 ...
        ,'NeurCont Toolbox/Auxiliary Blocks',-4 ...
        ,'NeurCont Toolbox/Events Transmission Blocks',-3 ...
        ,'NeurCont Toolbox/Quick Insert',-2 ...
        ,'NeurCont Toolbox/Quick Insert/Neural Blocks',-5 ...
        ,'NeurCont Toolbox/Quick Insert/Secondary Blocks',-4 ...
        ,'NeurCont Toolbox/Quick Insert/Events Transmission Blocks',-3} ...
    );
end

